site_name: Curso Dart & Flutter 

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      accent: deep orange    
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.indexes 
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.path
    - toc.follow

repo_url: https://github.com/jalmx/curso-dart-flutter

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      pygments_lang_class: true
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
