site_name: Curso Dart & Flutter 

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - tables

plugins:
  - search